# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zlv/Projects/sourceforge/MassDelivery/spamteacher

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zlv/Projects/sourceforge/MassDelivery/spamteacher

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zlv/Projects/sourceforge/MassDelivery/spamteacher/CMakeFiles /home/zlv/Projects/sourceforge/MassDelivery/spamteacher/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zlv/Projects/sourceforge/MassDelivery/spamteacher/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SpamTeacher

# Build rule for target.
SpamTeacher: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SpamTeacher
.PHONY : SpamTeacher

# fast build rule for target.
SpamTeacher/fast:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/build
.PHONY : SpamTeacher/fast

#=============================================================================
# Target rules for targets named translations

# Build rule for target.
translations: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 translations
.PHONY : translations

# fast build rule for target.
translations/fast:
	$(MAKE) -f CMakeFiles/translations.dir/build.make CMakeFiles/translations.dir/build
.PHONY : translations/fast

src/Data.o: src/Data.cpp.o
.PHONY : src/Data.o

# target to build an object file
src/Data.cpp.o:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/Data.cpp.o
.PHONY : src/Data.cpp.o

src/Data.i: src/Data.cpp.i
.PHONY : src/Data.i

# target to preprocess a source file
src/Data.cpp.i:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/Data.cpp.i
.PHONY : src/Data.cpp.i

src/Data.s: src/Data.cpp.s
.PHONY : src/Data.s

# target to generate assembly for a file
src/Data.cpp.s:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/Data.cpp.s
.PHONY : src/Data.cpp.s

src/func.o: src/func.cpp.o
.PHONY : src/func.o

# target to build an object file
src/func.cpp.o:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/func.cpp.o
.PHONY : src/func.cpp.o

src/func.i: src/func.cpp.i
.PHONY : src/func.i

# target to preprocess a source file
src/func.cpp.i:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/func.cpp.i
.PHONY : src/func.cpp.i

src/func.s: src/func.cpp.s
.PHONY : src/func.s

# target to generate assembly for a file
src/func.cpp.s:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/func.cpp.s
.PHONY : src/func.cpp.s

src/interface/qt/About.o: src/interface/qt/About.cpp.o
.PHONY : src/interface/qt/About.o

# target to build an object file
src/interface/qt/About.cpp.o:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/About.cpp.o
.PHONY : src/interface/qt/About.cpp.o

src/interface/qt/About.i: src/interface/qt/About.cpp.i
.PHONY : src/interface/qt/About.i

# target to preprocess a source file
src/interface/qt/About.cpp.i:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/About.cpp.i
.PHONY : src/interface/qt/About.cpp.i

src/interface/qt/About.s: src/interface/qt/About.cpp.s
.PHONY : src/interface/qt/About.s

# target to generate assembly for a file
src/interface/qt/About.cpp.s:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/About.cpp.s
.PHONY : src/interface/qt/About.cpp.s

src/interface/qt/AddMultReceiverWindow.o: src/interface/qt/AddMultReceiverWindow.cpp.o
.PHONY : src/interface/qt/AddMultReceiverWindow.o

# target to build an object file
src/interface/qt/AddMultReceiverWindow.cpp.o:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/AddMultReceiverWindow.cpp.o
.PHONY : src/interface/qt/AddMultReceiverWindow.cpp.o

src/interface/qt/AddMultReceiverWindow.i: src/interface/qt/AddMultReceiverWindow.cpp.i
.PHONY : src/interface/qt/AddMultReceiverWindow.i

# target to preprocess a source file
src/interface/qt/AddMultReceiverWindow.cpp.i:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/AddMultReceiverWindow.cpp.i
.PHONY : src/interface/qt/AddMultReceiverWindow.cpp.i

src/interface/qt/AddMultReceiverWindow.s: src/interface/qt/AddMultReceiverWindow.cpp.s
.PHONY : src/interface/qt/AddMultReceiverWindow.s

# target to generate assembly for a file
src/interface/qt/AddMultReceiverWindow.cpp.s:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/AddMultReceiverWindow.cpp.s
.PHONY : src/interface/qt/AddMultReceiverWindow.cpp.s

src/interface/qt/AddReceiverWindow.o: src/interface/qt/AddReceiverWindow.cpp.o
.PHONY : src/interface/qt/AddReceiverWindow.o

# target to build an object file
src/interface/qt/AddReceiverWindow.cpp.o:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/AddReceiverWindow.cpp.o
.PHONY : src/interface/qt/AddReceiverWindow.cpp.o

src/interface/qt/AddReceiverWindow.i: src/interface/qt/AddReceiverWindow.cpp.i
.PHONY : src/interface/qt/AddReceiverWindow.i

# target to preprocess a source file
src/interface/qt/AddReceiverWindow.cpp.i:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/AddReceiverWindow.cpp.i
.PHONY : src/interface/qt/AddReceiverWindow.cpp.i

src/interface/qt/AddReceiverWindow.s: src/interface/qt/AddReceiverWindow.cpp.s
.PHONY : src/interface/qt/AddReceiverWindow.s

# target to generate assembly for a file
src/interface/qt/AddReceiverWindow.cpp.s:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/AddReceiverWindow.cpp.s
.PHONY : src/interface/qt/AddReceiverWindow.cpp.s

src/interface/qt/AtachmentWindow.o: src/interface/qt/AtachmentWindow.cpp.o
.PHONY : src/interface/qt/AtachmentWindow.o

# target to build an object file
src/interface/qt/AtachmentWindow.cpp.o:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/AtachmentWindow.cpp.o
.PHONY : src/interface/qt/AtachmentWindow.cpp.o

src/interface/qt/AtachmentWindow.i: src/interface/qt/AtachmentWindow.cpp.i
.PHONY : src/interface/qt/AtachmentWindow.i

# target to preprocess a source file
src/interface/qt/AtachmentWindow.cpp.i:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/AtachmentWindow.cpp.i
.PHONY : src/interface/qt/AtachmentWindow.cpp.i

src/interface/qt/AtachmentWindow.s: src/interface/qt/AtachmentWindow.cpp.s
.PHONY : src/interface/qt/AtachmentWindow.s

# target to generate assembly for a file
src/interface/qt/AtachmentWindow.cpp.s:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/AtachmentWindow.cpp.s
.PHONY : src/interface/qt/AtachmentWindow.cpp.s

src/interface/qt/BaseWindow.o: src/interface/qt/BaseWindow.cpp.o
.PHONY : src/interface/qt/BaseWindow.o

# target to build an object file
src/interface/qt/BaseWindow.cpp.o:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/BaseWindow.cpp.o
.PHONY : src/interface/qt/BaseWindow.cpp.o

src/interface/qt/BaseWindow.i: src/interface/qt/BaseWindow.cpp.i
.PHONY : src/interface/qt/BaseWindow.i

# target to preprocess a source file
src/interface/qt/BaseWindow.cpp.i:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/BaseWindow.cpp.i
.PHONY : src/interface/qt/BaseWindow.cpp.i

src/interface/qt/BaseWindow.s: src/interface/qt/BaseWindow.cpp.s
.PHONY : src/interface/qt/BaseWindow.s

# target to generate assembly for a file
src/interface/qt/BaseWindow.cpp.s:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/BaseWindow.cpp.s
.PHONY : src/interface/qt/BaseWindow.cpp.s

src/interface/qt/Delegate.o: src/interface/qt/Delegate.cpp.o
.PHONY : src/interface/qt/Delegate.o

# target to build an object file
src/interface/qt/Delegate.cpp.o:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/Delegate.cpp.o
.PHONY : src/interface/qt/Delegate.cpp.o

src/interface/qt/Delegate.i: src/interface/qt/Delegate.cpp.i
.PHONY : src/interface/qt/Delegate.i

# target to preprocess a source file
src/interface/qt/Delegate.cpp.i:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/Delegate.cpp.i
.PHONY : src/interface/qt/Delegate.cpp.i

src/interface/qt/Delegate.s: src/interface/qt/Delegate.cpp.s
.PHONY : src/interface/qt/Delegate.s

# target to generate assembly for a file
src/interface/qt/Delegate.cpp.s:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/Delegate.cpp.s
.PHONY : src/interface/qt/Delegate.cpp.s

src/interface/qt/GenderWindow.o: src/interface/qt/GenderWindow.cpp.o
.PHONY : src/interface/qt/GenderWindow.o

# target to build an object file
src/interface/qt/GenderWindow.cpp.o:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/GenderWindow.cpp.o
.PHONY : src/interface/qt/GenderWindow.cpp.o

src/interface/qt/GenderWindow.i: src/interface/qt/GenderWindow.cpp.i
.PHONY : src/interface/qt/GenderWindow.i

# target to preprocess a source file
src/interface/qt/GenderWindow.cpp.i:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/GenderWindow.cpp.i
.PHONY : src/interface/qt/GenderWindow.cpp.i

src/interface/qt/GenderWindow.s: src/interface/qt/GenderWindow.cpp.s
.PHONY : src/interface/qt/GenderWindow.s

# target to generate assembly for a file
src/interface/qt/GenderWindow.cpp.s:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/GenderWindow.cpp.s
.PHONY : src/interface/qt/GenderWindow.cpp.s

src/interface/qt/MainWindow.o: src/interface/qt/MainWindow.cpp.o
.PHONY : src/interface/qt/MainWindow.o

# target to build an object file
src/interface/qt/MainWindow.cpp.o:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/MainWindow.cpp.o
.PHONY : src/interface/qt/MainWindow.cpp.o

src/interface/qt/MainWindow.i: src/interface/qt/MainWindow.cpp.i
.PHONY : src/interface/qt/MainWindow.i

# target to preprocess a source file
src/interface/qt/MainWindow.cpp.i:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/MainWindow.cpp.i
.PHONY : src/interface/qt/MainWindow.cpp.i

src/interface/qt/MainWindow.s: src/interface/qt/MainWindow.cpp.s
.PHONY : src/interface/qt/MainWindow.s

# target to generate assembly for a file
src/interface/qt/MainWindow.cpp.s:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/MainWindow.cpp.s
.PHONY : src/interface/qt/MainWindow.cpp.s

src/interface/qt/PassWindow.o: src/interface/qt/PassWindow.cpp.o
.PHONY : src/interface/qt/PassWindow.o

# target to build an object file
src/interface/qt/PassWindow.cpp.o:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/PassWindow.cpp.o
.PHONY : src/interface/qt/PassWindow.cpp.o

src/interface/qt/PassWindow.i: src/interface/qt/PassWindow.cpp.i
.PHONY : src/interface/qt/PassWindow.i

# target to preprocess a source file
src/interface/qt/PassWindow.cpp.i:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/PassWindow.cpp.i
.PHONY : src/interface/qt/PassWindow.cpp.i

src/interface/qt/PassWindow.s: src/interface/qt/PassWindow.cpp.s
.PHONY : src/interface/qt/PassWindow.s

# target to generate assembly for a file
src/interface/qt/PassWindow.cpp.s:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/PassWindow.cpp.s
.PHONY : src/interface/qt/PassWindow.cpp.s

src/interface/qt/ReceiverWindow.o: src/interface/qt/ReceiverWindow.cpp.o
.PHONY : src/interface/qt/ReceiverWindow.o

# target to build an object file
src/interface/qt/ReceiverWindow.cpp.o:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/ReceiverWindow.cpp.o
.PHONY : src/interface/qt/ReceiverWindow.cpp.o

src/interface/qt/ReceiverWindow.i: src/interface/qt/ReceiverWindow.cpp.i
.PHONY : src/interface/qt/ReceiverWindow.i

# target to preprocess a source file
src/interface/qt/ReceiverWindow.cpp.i:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/ReceiverWindow.cpp.i
.PHONY : src/interface/qt/ReceiverWindow.cpp.i

src/interface/qt/ReceiverWindow.s: src/interface/qt/ReceiverWindow.cpp.s
.PHONY : src/interface/qt/ReceiverWindow.s

# target to generate assembly for a file
src/interface/qt/ReceiverWindow.cpp.s:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/ReceiverWindow.cpp.s
.PHONY : src/interface/qt/ReceiverWindow.cpp.s

src/interface/qt/SendWindow.o: src/interface/qt/SendWindow.cpp.o
.PHONY : src/interface/qt/SendWindow.o

# target to build an object file
src/interface/qt/SendWindow.cpp.o:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/SendWindow.cpp.o
.PHONY : src/interface/qt/SendWindow.cpp.o

src/interface/qt/SendWindow.i: src/interface/qt/SendWindow.cpp.i
.PHONY : src/interface/qt/SendWindow.i

# target to preprocess a source file
src/interface/qt/SendWindow.cpp.i:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/SendWindow.cpp.i
.PHONY : src/interface/qt/SendWindow.cpp.i

src/interface/qt/SendWindow.s: src/interface/qt/SendWindow.cpp.s
.PHONY : src/interface/qt/SendWindow.s

# target to generate assembly for a file
src/interface/qt/SendWindow.cpp.s:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/SendWindow.cpp.s
.PHONY : src/interface/qt/SendWindow.cpp.s

src/interface/qt/SenderWindow.o: src/interface/qt/SenderWindow.cpp.o
.PHONY : src/interface/qt/SenderWindow.o

# target to build an object file
src/interface/qt/SenderWindow.cpp.o:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/SenderWindow.cpp.o
.PHONY : src/interface/qt/SenderWindow.cpp.o

src/interface/qt/SenderWindow.i: src/interface/qt/SenderWindow.cpp.i
.PHONY : src/interface/qt/SenderWindow.i

# target to preprocess a source file
src/interface/qt/SenderWindow.cpp.i:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/SenderWindow.cpp.i
.PHONY : src/interface/qt/SenderWindow.cpp.i

src/interface/qt/SenderWindow.s: src/interface/qt/SenderWindow.cpp.s
.PHONY : src/interface/qt/SenderWindow.s

# target to generate assembly for a file
src/interface/qt/SenderWindow.cpp.s:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/SenderWindow.cpp.s
.PHONY : src/interface/qt/SenderWindow.cpp.s

src/interface/qt/main.o: src/interface/qt/main.cpp.o
.PHONY : src/interface/qt/main.o

# target to build an object file
src/interface/qt/main.cpp.o:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/main.cpp.o
.PHONY : src/interface/qt/main.cpp.o

src/interface/qt/main.i: src/interface/qt/main.cpp.i
.PHONY : src/interface/qt/main.i

# target to preprocess a source file
src/interface/qt/main.cpp.i:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/main.cpp.i
.PHONY : src/interface/qt/main.cpp.i

src/interface/qt/main.s: src/interface/qt/main.cpp.s
.PHONY : src/interface/qt/main.s

# target to generate assembly for a file
src/interface/qt/main.cpp.s:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/main.cpp.s
.PHONY : src/interface/qt/main.cpp.s

src/interface/qt/moc_About.o: src/interface/qt/moc_About.cxx.o
.PHONY : src/interface/qt/moc_About.o

# target to build an object file
src/interface/qt/moc_About.cxx.o:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/moc_About.cxx.o
.PHONY : src/interface/qt/moc_About.cxx.o

src/interface/qt/moc_About.i: src/interface/qt/moc_About.cxx.i
.PHONY : src/interface/qt/moc_About.i

# target to preprocess a source file
src/interface/qt/moc_About.cxx.i:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/moc_About.cxx.i
.PHONY : src/interface/qt/moc_About.cxx.i

src/interface/qt/moc_About.s: src/interface/qt/moc_About.cxx.s
.PHONY : src/interface/qt/moc_About.s

# target to generate assembly for a file
src/interface/qt/moc_About.cxx.s:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/moc_About.cxx.s
.PHONY : src/interface/qt/moc_About.cxx.s

src/interface/qt/moc_AddMultReceiverWindow.o: src/interface/qt/moc_AddMultReceiverWindow.cxx.o
.PHONY : src/interface/qt/moc_AddMultReceiverWindow.o

# target to build an object file
src/interface/qt/moc_AddMultReceiverWindow.cxx.o:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/moc_AddMultReceiverWindow.cxx.o
.PHONY : src/interface/qt/moc_AddMultReceiverWindow.cxx.o

src/interface/qt/moc_AddMultReceiverWindow.i: src/interface/qt/moc_AddMultReceiverWindow.cxx.i
.PHONY : src/interface/qt/moc_AddMultReceiverWindow.i

# target to preprocess a source file
src/interface/qt/moc_AddMultReceiverWindow.cxx.i:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/moc_AddMultReceiverWindow.cxx.i
.PHONY : src/interface/qt/moc_AddMultReceiverWindow.cxx.i

src/interface/qt/moc_AddMultReceiverWindow.s: src/interface/qt/moc_AddMultReceiverWindow.cxx.s
.PHONY : src/interface/qt/moc_AddMultReceiverWindow.s

# target to generate assembly for a file
src/interface/qt/moc_AddMultReceiverWindow.cxx.s:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/moc_AddMultReceiverWindow.cxx.s
.PHONY : src/interface/qt/moc_AddMultReceiverWindow.cxx.s

src/interface/qt/moc_AddReceiverWindow.o: src/interface/qt/moc_AddReceiverWindow.cxx.o
.PHONY : src/interface/qt/moc_AddReceiverWindow.o

# target to build an object file
src/interface/qt/moc_AddReceiverWindow.cxx.o:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/moc_AddReceiverWindow.cxx.o
.PHONY : src/interface/qt/moc_AddReceiverWindow.cxx.o

src/interface/qt/moc_AddReceiverWindow.i: src/interface/qt/moc_AddReceiverWindow.cxx.i
.PHONY : src/interface/qt/moc_AddReceiverWindow.i

# target to preprocess a source file
src/interface/qt/moc_AddReceiverWindow.cxx.i:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/moc_AddReceiverWindow.cxx.i
.PHONY : src/interface/qt/moc_AddReceiverWindow.cxx.i

src/interface/qt/moc_AddReceiverWindow.s: src/interface/qt/moc_AddReceiverWindow.cxx.s
.PHONY : src/interface/qt/moc_AddReceiverWindow.s

# target to generate assembly for a file
src/interface/qt/moc_AddReceiverWindow.cxx.s:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/moc_AddReceiverWindow.cxx.s
.PHONY : src/interface/qt/moc_AddReceiverWindow.cxx.s

src/interface/qt/moc_AtachmentWindow.o: src/interface/qt/moc_AtachmentWindow.cxx.o
.PHONY : src/interface/qt/moc_AtachmentWindow.o

# target to build an object file
src/interface/qt/moc_AtachmentWindow.cxx.o:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/moc_AtachmentWindow.cxx.o
.PHONY : src/interface/qt/moc_AtachmentWindow.cxx.o

src/interface/qt/moc_AtachmentWindow.i: src/interface/qt/moc_AtachmentWindow.cxx.i
.PHONY : src/interface/qt/moc_AtachmentWindow.i

# target to preprocess a source file
src/interface/qt/moc_AtachmentWindow.cxx.i:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/moc_AtachmentWindow.cxx.i
.PHONY : src/interface/qt/moc_AtachmentWindow.cxx.i

src/interface/qt/moc_AtachmentWindow.s: src/interface/qt/moc_AtachmentWindow.cxx.s
.PHONY : src/interface/qt/moc_AtachmentWindow.s

# target to generate assembly for a file
src/interface/qt/moc_AtachmentWindow.cxx.s:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/moc_AtachmentWindow.cxx.s
.PHONY : src/interface/qt/moc_AtachmentWindow.cxx.s

src/interface/qt/moc_BaseWindow.o: src/interface/qt/moc_BaseWindow.cxx.o
.PHONY : src/interface/qt/moc_BaseWindow.o

# target to build an object file
src/interface/qt/moc_BaseWindow.cxx.o:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/moc_BaseWindow.cxx.o
.PHONY : src/interface/qt/moc_BaseWindow.cxx.o

src/interface/qt/moc_BaseWindow.i: src/interface/qt/moc_BaseWindow.cxx.i
.PHONY : src/interface/qt/moc_BaseWindow.i

# target to preprocess a source file
src/interface/qt/moc_BaseWindow.cxx.i:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/moc_BaseWindow.cxx.i
.PHONY : src/interface/qt/moc_BaseWindow.cxx.i

src/interface/qt/moc_BaseWindow.s: src/interface/qt/moc_BaseWindow.cxx.s
.PHONY : src/interface/qt/moc_BaseWindow.s

# target to generate assembly for a file
src/interface/qt/moc_BaseWindow.cxx.s:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/moc_BaseWindow.cxx.s
.PHONY : src/interface/qt/moc_BaseWindow.cxx.s

src/interface/qt/moc_Delegate.o: src/interface/qt/moc_Delegate.cxx.o
.PHONY : src/interface/qt/moc_Delegate.o

# target to build an object file
src/interface/qt/moc_Delegate.cxx.o:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/moc_Delegate.cxx.o
.PHONY : src/interface/qt/moc_Delegate.cxx.o

src/interface/qt/moc_Delegate.i: src/interface/qt/moc_Delegate.cxx.i
.PHONY : src/interface/qt/moc_Delegate.i

# target to preprocess a source file
src/interface/qt/moc_Delegate.cxx.i:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/moc_Delegate.cxx.i
.PHONY : src/interface/qt/moc_Delegate.cxx.i

src/interface/qt/moc_Delegate.s: src/interface/qt/moc_Delegate.cxx.s
.PHONY : src/interface/qt/moc_Delegate.s

# target to generate assembly for a file
src/interface/qt/moc_Delegate.cxx.s:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/moc_Delegate.cxx.s
.PHONY : src/interface/qt/moc_Delegate.cxx.s

src/interface/qt/moc_GenderWindow.o: src/interface/qt/moc_GenderWindow.cxx.o
.PHONY : src/interface/qt/moc_GenderWindow.o

# target to build an object file
src/interface/qt/moc_GenderWindow.cxx.o:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/moc_GenderWindow.cxx.o
.PHONY : src/interface/qt/moc_GenderWindow.cxx.o

src/interface/qt/moc_GenderWindow.i: src/interface/qt/moc_GenderWindow.cxx.i
.PHONY : src/interface/qt/moc_GenderWindow.i

# target to preprocess a source file
src/interface/qt/moc_GenderWindow.cxx.i:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/moc_GenderWindow.cxx.i
.PHONY : src/interface/qt/moc_GenderWindow.cxx.i

src/interface/qt/moc_GenderWindow.s: src/interface/qt/moc_GenderWindow.cxx.s
.PHONY : src/interface/qt/moc_GenderWindow.s

# target to generate assembly for a file
src/interface/qt/moc_GenderWindow.cxx.s:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/moc_GenderWindow.cxx.s
.PHONY : src/interface/qt/moc_GenderWindow.cxx.s

src/interface/qt/moc_MainWindow.o: src/interface/qt/moc_MainWindow.cxx.o
.PHONY : src/interface/qt/moc_MainWindow.o

# target to build an object file
src/interface/qt/moc_MainWindow.cxx.o:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/moc_MainWindow.cxx.o
.PHONY : src/interface/qt/moc_MainWindow.cxx.o

src/interface/qt/moc_MainWindow.i: src/interface/qt/moc_MainWindow.cxx.i
.PHONY : src/interface/qt/moc_MainWindow.i

# target to preprocess a source file
src/interface/qt/moc_MainWindow.cxx.i:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/moc_MainWindow.cxx.i
.PHONY : src/interface/qt/moc_MainWindow.cxx.i

src/interface/qt/moc_MainWindow.s: src/interface/qt/moc_MainWindow.cxx.s
.PHONY : src/interface/qt/moc_MainWindow.s

# target to generate assembly for a file
src/interface/qt/moc_MainWindow.cxx.s:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/moc_MainWindow.cxx.s
.PHONY : src/interface/qt/moc_MainWindow.cxx.s

src/interface/qt/moc_PassWindow.o: src/interface/qt/moc_PassWindow.cxx.o
.PHONY : src/interface/qt/moc_PassWindow.o

# target to build an object file
src/interface/qt/moc_PassWindow.cxx.o:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/moc_PassWindow.cxx.o
.PHONY : src/interface/qt/moc_PassWindow.cxx.o

src/interface/qt/moc_PassWindow.i: src/interface/qt/moc_PassWindow.cxx.i
.PHONY : src/interface/qt/moc_PassWindow.i

# target to preprocess a source file
src/interface/qt/moc_PassWindow.cxx.i:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/moc_PassWindow.cxx.i
.PHONY : src/interface/qt/moc_PassWindow.cxx.i

src/interface/qt/moc_PassWindow.s: src/interface/qt/moc_PassWindow.cxx.s
.PHONY : src/interface/qt/moc_PassWindow.s

# target to generate assembly for a file
src/interface/qt/moc_PassWindow.cxx.s:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/moc_PassWindow.cxx.s
.PHONY : src/interface/qt/moc_PassWindow.cxx.s

src/interface/qt/moc_ReceiverWindow.o: src/interface/qt/moc_ReceiverWindow.cxx.o
.PHONY : src/interface/qt/moc_ReceiverWindow.o

# target to build an object file
src/interface/qt/moc_ReceiverWindow.cxx.o:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/moc_ReceiverWindow.cxx.o
.PHONY : src/interface/qt/moc_ReceiverWindow.cxx.o

src/interface/qt/moc_ReceiverWindow.i: src/interface/qt/moc_ReceiverWindow.cxx.i
.PHONY : src/interface/qt/moc_ReceiverWindow.i

# target to preprocess a source file
src/interface/qt/moc_ReceiverWindow.cxx.i:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/moc_ReceiverWindow.cxx.i
.PHONY : src/interface/qt/moc_ReceiverWindow.cxx.i

src/interface/qt/moc_ReceiverWindow.s: src/interface/qt/moc_ReceiverWindow.cxx.s
.PHONY : src/interface/qt/moc_ReceiverWindow.s

# target to generate assembly for a file
src/interface/qt/moc_ReceiverWindow.cxx.s:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/moc_ReceiverWindow.cxx.s
.PHONY : src/interface/qt/moc_ReceiverWindow.cxx.s

src/interface/qt/moc_SendWindow.o: src/interface/qt/moc_SendWindow.cxx.o
.PHONY : src/interface/qt/moc_SendWindow.o

# target to build an object file
src/interface/qt/moc_SendWindow.cxx.o:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/moc_SendWindow.cxx.o
.PHONY : src/interface/qt/moc_SendWindow.cxx.o

src/interface/qt/moc_SendWindow.i: src/interface/qt/moc_SendWindow.cxx.i
.PHONY : src/interface/qt/moc_SendWindow.i

# target to preprocess a source file
src/interface/qt/moc_SendWindow.cxx.i:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/moc_SendWindow.cxx.i
.PHONY : src/interface/qt/moc_SendWindow.cxx.i

src/interface/qt/moc_SendWindow.s: src/interface/qt/moc_SendWindow.cxx.s
.PHONY : src/interface/qt/moc_SendWindow.s

# target to generate assembly for a file
src/interface/qt/moc_SendWindow.cxx.s:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/moc_SendWindow.cxx.s
.PHONY : src/interface/qt/moc_SendWindow.cxx.s

src/interface/qt/moc_SenderWindow.o: src/interface/qt/moc_SenderWindow.cxx.o
.PHONY : src/interface/qt/moc_SenderWindow.o

# target to build an object file
src/interface/qt/moc_SenderWindow.cxx.o:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/moc_SenderWindow.cxx.o
.PHONY : src/interface/qt/moc_SenderWindow.cxx.o

src/interface/qt/moc_SenderWindow.i: src/interface/qt/moc_SenderWindow.cxx.i
.PHONY : src/interface/qt/moc_SenderWindow.i

# target to preprocess a source file
src/interface/qt/moc_SenderWindow.cxx.i:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/moc_SenderWindow.cxx.i
.PHONY : src/interface/qt/moc_SenderWindow.cxx.i

src/interface/qt/moc_SenderWindow.s: src/interface/qt/moc_SenderWindow.cxx.s
.PHONY : src/interface/qt/moc_SenderWindow.s

# target to generate assembly for a file
src/interface/qt/moc_SenderWindow.cxx.s:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/interface/qt/moc_SenderWindow.cxx.s
.PHONY : src/interface/qt/moc_SenderWindow.cxx.s

src/moc_Data.o: src/moc_Data.cxx.o
.PHONY : src/moc_Data.o

# target to build an object file
src/moc_Data.cxx.o:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/moc_Data.cxx.o
.PHONY : src/moc_Data.cxx.o

src/moc_Data.i: src/moc_Data.cxx.i
.PHONY : src/moc_Data.i

# target to preprocess a source file
src/moc_Data.cxx.i:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/moc_Data.cxx.i
.PHONY : src/moc_Data.cxx.i

src/moc_Data.s: src/moc_Data.cxx.s
.PHONY : src/moc_Data.s

# target to generate assembly for a file
src/moc_Data.cxx.s:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/moc_Data.cxx.s
.PHONY : src/moc_Data.cxx.s

src/moc_Receiver.o: src/moc_Receiver.cxx.o
.PHONY : src/moc_Receiver.o

# target to build an object file
src/moc_Receiver.cxx.o:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/moc_Receiver.cxx.o
.PHONY : src/moc_Receiver.cxx.o

src/moc_Receiver.i: src/moc_Receiver.cxx.i
.PHONY : src/moc_Receiver.i

# target to preprocess a source file
src/moc_Receiver.cxx.i:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/moc_Receiver.cxx.i
.PHONY : src/moc_Receiver.cxx.i

src/moc_Receiver.s: src/moc_Receiver.cxx.s
.PHONY : src/moc_Receiver.s

# target to generate assembly for a file
src/moc_Receiver.cxx.s:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/moc_Receiver.cxx.s
.PHONY : src/moc_Receiver.cxx.s

src/moc_func.o: src/moc_func.cxx.o
.PHONY : src/moc_func.o

# target to build an object file
src/moc_func.cxx.o:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/moc_func.cxx.o
.PHONY : src/moc_func.cxx.o

src/moc_func.i: src/moc_func.cxx.i
.PHONY : src/moc_func.i

# target to preprocess a source file
src/moc_func.cxx.i:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/moc_func.cxx.i
.PHONY : src/moc_func.cxx.i

src/moc_func.s: src/moc_func.cxx.s
.PHONY : src/moc_func.s

# target to generate assembly for a file
src/moc_func.cxx.s:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/moc_func.cxx.s
.PHONY : src/moc_func.cxx.s

src/send/base64.o: src/send/base64.cpp.o
.PHONY : src/send/base64.o

# target to build an object file
src/send/base64.cpp.o:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/send/base64.cpp.o
.PHONY : src/send/base64.cpp.o

src/send/base64.i: src/send/base64.cpp.i
.PHONY : src/send/base64.i

# target to preprocess a source file
src/send/base64.cpp.i:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/send/base64.cpp.i
.PHONY : src/send/base64.cpp.i

src/send/base64.s: src/send/base64.cpp.s
.PHONY : src/send/base64.s

# target to generate assembly for a file
src/send/base64.cpp.s:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/send/base64.cpp.s
.PHONY : src/send/base64.cpp.s

src/send/moc_base64.o: src/send/moc_base64.cxx.o
.PHONY : src/send/moc_base64.o

# target to build an object file
src/send/moc_base64.cxx.o:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/send/moc_base64.cxx.o
.PHONY : src/send/moc_base64.cxx.o

src/send/moc_base64.i: src/send/moc_base64.cxx.i
.PHONY : src/send/moc_base64.i

# target to preprocess a source file
src/send/moc_base64.cxx.i:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/send/moc_base64.cxx.i
.PHONY : src/send/moc_base64.cxx.i

src/send/moc_base64.s: src/send/moc_base64.cxx.s
.PHONY : src/send/moc_base64.s

# target to generate assembly for a file
src/send/moc_base64.cxx.s:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/send/moc_base64.cxx.s
.PHONY : src/send/moc_base64.cxx.s

src/send/moc_send.o: src/send/moc_send.cxx.o
.PHONY : src/send/moc_send.o

# target to build an object file
src/send/moc_send.cxx.o:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/send/moc_send.cxx.o
.PHONY : src/send/moc_send.cxx.o

src/send/moc_send.i: src/send/moc_send.cxx.i
.PHONY : src/send/moc_send.i

# target to preprocess a source file
src/send/moc_send.cxx.i:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/send/moc_send.cxx.i
.PHONY : src/send/moc_send.cxx.i

src/send/moc_send.s: src/send/moc_send.cxx.s
.PHONY : src/send/moc_send.s

# target to generate assembly for a file
src/send/moc_send.cxx.s:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/send/moc_send.cxx.s
.PHONY : src/send/moc_send.cxx.s

src/send/moc_u82w1251.o: src/send/moc_u82w1251.cxx.o
.PHONY : src/send/moc_u82w1251.o

# target to build an object file
src/send/moc_u82w1251.cxx.o:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/send/moc_u82w1251.cxx.o
.PHONY : src/send/moc_u82w1251.cxx.o

src/send/moc_u82w1251.i: src/send/moc_u82w1251.cxx.i
.PHONY : src/send/moc_u82w1251.i

# target to preprocess a source file
src/send/moc_u82w1251.cxx.i:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/send/moc_u82w1251.cxx.i
.PHONY : src/send/moc_u82w1251.cxx.i

src/send/moc_u82w1251.s: src/send/moc_u82w1251.cxx.s
.PHONY : src/send/moc_u82w1251.s

# target to generate assembly for a file
src/send/moc_u82w1251.cxx.s:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/send/moc_u82w1251.cxx.s
.PHONY : src/send/moc_u82w1251.cxx.s

src/send/send.o: src/send/send.cpp.o
.PHONY : src/send/send.o

# target to build an object file
src/send/send.cpp.o:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/send/send.cpp.o
.PHONY : src/send/send.cpp.o

src/send/send.i: src/send/send.cpp.i
.PHONY : src/send/send.i

# target to preprocess a source file
src/send/send.cpp.i:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/send/send.cpp.i
.PHONY : src/send/send.cpp.i

src/send/send.s: src/send/send.cpp.s
.PHONY : src/send/send.s

# target to generate assembly for a file
src/send/send.cpp.s:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/send/send.cpp.s
.PHONY : src/send/send.cpp.s

src/send/u82w1251.o: src/send/u82w1251.cpp.o
.PHONY : src/send/u82w1251.o

# target to build an object file
src/send/u82w1251.cpp.o:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/send/u82w1251.cpp.o
.PHONY : src/send/u82w1251.cpp.o

src/send/u82w1251.i: src/send/u82w1251.cpp.i
.PHONY : src/send/u82w1251.i

# target to preprocess a source file
src/send/u82w1251.cpp.i:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/send/u82w1251.cpp.i
.PHONY : src/send/u82w1251.cpp.i

src/send/u82w1251.s: src/send/u82w1251.cpp.s
.PHONY : src/send/u82w1251.s

# target to generate assembly for a file
src/send/u82w1251.cpp.s:
	$(MAKE) -f CMakeFiles/SpamTeacher.dir/build.make CMakeFiles/SpamTeacher.dir/src/send/u82w1251.cpp.s
.PHONY : src/send/u82w1251.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... SpamTeacher"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... translations"
	@echo "... src/Data.o"
	@echo "... src/Data.i"
	@echo "... src/Data.s"
	@echo "... src/func.o"
	@echo "... src/func.i"
	@echo "... src/func.s"
	@echo "... src/interface/qt/About.o"
	@echo "... src/interface/qt/About.i"
	@echo "... src/interface/qt/About.s"
	@echo "... src/interface/qt/AddMultReceiverWindow.o"
	@echo "... src/interface/qt/AddMultReceiverWindow.i"
	@echo "... src/interface/qt/AddMultReceiverWindow.s"
	@echo "... src/interface/qt/AddReceiverWindow.o"
	@echo "... src/interface/qt/AddReceiverWindow.i"
	@echo "... src/interface/qt/AddReceiverWindow.s"
	@echo "... src/interface/qt/AtachmentWindow.o"
	@echo "... src/interface/qt/AtachmentWindow.i"
	@echo "... src/interface/qt/AtachmentWindow.s"
	@echo "... src/interface/qt/BaseWindow.o"
	@echo "... src/interface/qt/BaseWindow.i"
	@echo "... src/interface/qt/BaseWindow.s"
	@echo "... src/interface/qt/Delegate.o"
	@echo "... src/interface/qt/Delegate.i"
	@echo "... src/interface/qt/Delegate.s"
	@echo "... src/interface/qt/GenderWindow.o"
	@echo "... src/interface/qt/GenderWindow.i"
	@echo "... src/interface/qt/GenderWindow.s"
	@echo "... src/interface/qt/MainWindow.o"
	@echo "... src/interface/qt/MainWindow.i"
	@echo "... src/interface/qt/MainWindow.s"
	@echo "... src/interface/qt/PassWindow.o"
	@echo "... src/interface/qt/PassWindow.i"
	@echo "... src/interface/qt/PassWindow.s"
	@echo "... src/interface/qt/ReceiverWindow.o"
	@echo "... src/interface/qt/ReceiverWindow.i"
	@echo "... src/interface/qt/ReceiverWindow.s"
	@echo "... src/interface/qt/SendWindow.o"
	@echo "... src/interface/qt/SendWindow.i"
	@echo "... src/interface/qt/SendWindow.s"
	@echo "... src/interface/qt/SenderWindow.o"
	@echo "... src/interface/qt/SenderWindow.i"
	@echo "... src/interface/qt/SenderWindow.s"
	@echo "... src/interface/qt/main.o"
	@echo "... src/interface/qt/main.i"
	@echo "... src/interface/qt/main.s"
	@echo "... src/interface/qt/moc_About.o"
	@echo "... src/interface/qt/moc_About.i"
	@echo "... src/interface/qt/moc_About.s"
	@echo "... src/interface/qt/moc_AddMultReceiverWindow.o"
	@echo "... src/interface/qt/moc_AddMultReceiverWindow.i"
	@echo "... src/interface/qt/moc_AddMultReceiverWindow.s"
	@echo "... src/interface/qt/moc_AddReceiverWindow.o"
	@echo "... src/interface/qt/moc_AddReceiverWindow.i"
	@echo "... src/interface/qt/moc_AddReceiverWindow.s"
	@echo "... src/interface/qt/moc_AtachmentWindow.o"
	@echo "... src/interface/qt/moc_AtachmentWindow.i"
	@echo "... src/interface/qt/moc_AtachmentWindow.s"
	@echo "... src/interface/qt/moc_BaseWindow.o"
	@echo "... src/interface/qt/moc_BaseWindow.i"
	@echo "... src/interface/qt/moc_BaseWindow.s"
	@echo "... src/interface/qt/moc_Delegate.o"
	@echo "... src/interface/qt/moc_Delegate.i"
	@echo "... src/interface/qt/moc_Delegate.s"
	@echo "... src/interface/qt/moc_GenderWindow.o"
	@echo "... src/interface/qt/moc_GenderWindow.i"
	@echo "... src/interface/qt/moc_GenderWindow.s"
	@echo "... src/interface/qt/moc_MainWindow.o"
	@echo "... src/interface/qt/moc_MainWindow.i"
	@echo "... src/interface/qt/moc_MainWindow.s"
	@echo "... src/interface/qt/moc_PassWindow.o"
	@echo "... src/interface/qt/moc_PassWindow.i"
	@echo "... src/interface/qt/moc_PassWindow.s"
	@echo "... src/interface/qt/moc_ReceiverWindow.o"
	@echo "... src/interface/qt/moc_ReceiverWindow.i"
	@echo "... src/interface/qt/moc_ReceiverWindow.s"
	@echo "... src/interface/qt/moc_SendWindow.o"
	@echo "... src/interface/qt/moc_SendWindow.i"
	@echo "... src/interface/qt/moc_SendWindow.s"
	@echo "... src/interface/qt/moc_SenderWindow.o"
	@echo "... src/interface/qt/moc_SenderWindow.i"
	@echo "... src/interface/qt/moc_SenderWindow.s"
	@echo "... src/moc_Data.o"
	@echo "... src/moc_Data.i"
	@echo "... src/moc_Data.s"
	@echo "... src/moc_Receiver.o"
	@echo "... src/moc_Receiver.i"
	@echo "... src/moc_Receiver.s"
	@echo "... src/moc_func.o"
	@echo "... src/moc_func.i"
	@echo "... src/moc_func.s"
	@echo "... src/send/base64.o"
	@echo "... src/send/base64.i"
	@echo "... src/send/base64.s"
	@echo "... src/send/moc_base64.o"
	@echo "... src/send/moc_base64.i"
	@echo "... src/send/moc_base64.s"
	@echo "... src/send/moc_send.o"
	@echo "... src/send/moc_send.i"
	@echo "... src/send/moc_send.s"
	@echo "... src/send/moc_u82w1251.o"
	@echo "... src/send/moc_u82w1251.i"
	@echo "... src/send/moc_u82w1251.s"
	@echo "... src/send/send.o"
	@echo "... src/send/send.i"
	@echo "... src/send/send.s"
	@echo "... src/send/u82w1251.o"
	@echo "... src/send/u82w1251.i"
	@echo "... src/send/u82w1251.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

